# Generated by Django 5.1.6 on 2025-02-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_rename_torneios_times_torneios'),
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneios',
            name='campeao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='times.times'),
        ),
        migrations.AddField(
            model_name='torneios',
            name='finalistas',
            field=models.ManyToManyField(blank=True, related_name='finalista_em', to='times.times'),
        ),
    ]
