# Generated by Django 5.1.6 on 2025-02-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0003_torneios_artilheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneios',
            name='sigla',
            field=models.CharField(blank=True, help_text='Defina a sigla manualmente (ex: mg para Mineiro)', max_length=10, null=True),
        ),
    ]
