# Generated by Django 5.1.6 on 2025-02-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artilheiros', '0001_initial'),
        ('torneios', '0004_torneios_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='artilheiro',
            name='torneio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artilheiros', to='torneios.torneios'),
            preserve_default=False,
        ),
    ]
