# Generated by Django 5.1.6 on 2025-02-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participante', '0001_initial'),
        ('times', '0001_initial'),
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='participante.participantes')),
                ('times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.times')),
                ('torneios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.torneios')),
            ],
            options={
                'unique_together': {('participantes', 'torneios')},
            },
        ),
    ]
