# Generated by Django 5.1.6 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecao',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
