# Generated by Django 5.1.6 on 2025-02-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artilheiros', '0001_initial'),
        ('selecao', '0002_selecao_custom_selecao_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='artilheiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions_art', to='artilheiros.artilheiro'),
        ),
    ]
