# Generated by Django 5.1.6 on 2025-02-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Torneios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='torneios.torneios')),
            ],
        ),
    ]
