# Generated by Django 5.1.6 on 2025-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_rename_torneios_times_torneios'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='times_fotos/'),
        ),
    ]
